# Day 15 Assignment

__1. Create a 3x3x3 array with random values__

In [1]:
import numpy as np
q1=np.random.random((3,3,3))

print("Example for ",q1.shape," Array with Random Values","\n",q1)

Example for  (3, 3, 3)  Array with Random Values 
 [[[0.34021193 0.44705804 0.8785484 ]
  [0.44491102 0.07088335 0.47136455]
  [0.18812422 0.13969388 0.93069807]]

 [[0.78699658 0.13211739 0.05430579]
  [0.32500755 0.14446348 0.57157285]
  [0.626377   0.8675607  0.1859079 ]]

 [[0.34156852 0.81183133 0.54288539]
  [0.82252212 0.00125391 0.13071066]
  [0.23813357 0.22681109 0.86734711]]]


__2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal__

In [2]:
q2=np.zeros((5,5))
q2=np.diag(1+np.arange(4),k = -1)
print(q2.shape," matrix with values 1,2,3,4 just below the diagonal","\n",q2)

(5, 5)  matrix with values 1,2,3,4 just below the diagonal 
 [[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


__3.Create a 8x8 matrix and fill it with a checkerboard pattern__

In [3]:
q3=np.ones((8,8))
q3[::2,::2] = 0
q3[1::2,1::2] = 0
print("Checkboard Pattern",q3.shape," matrix","\n",q3)

Checkboard Pattern (8, 8)  matrix 
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


__4. Normalize a 5x5 random matrix__

In [4]:
q4= np.random.random((5,5))
print(q4.shape," Random Matrix\n",q4,"\n")
q4mx, q4mn = q4.max(), q4.min()
q4 = (q4 - q4mn)/(q4mx - q4mn)
print("Normalized ",q4.shape," matrix","\n",q4)

(5, 5)  Random Matrix
 [[0.24671656 0.83555221 0.63516501 0.41328117 0.04325159]
 [0.56786426 0.51697449 0.42683151 0.32185832 0.1612585 ]
 [0.12669659 0.70184649 0.35988442 0.18257537 0.84181211]
 [0.21352507 0.64755753 0.77939055 0.79304562 0.32258715]
 [0.76838406 0.43444665 0.70213796 0.10172022 0.29431978]] 

Normalized  (5, 5)  matrix 
 [[0.25478967 0.99216102 0.7412255  0.46337074 0.        ]
 [0.65694791 0.59322103 0.48033919 0.34888618 0.14777454]
 [0.10449428 0.82472759 0.39650449 0.17446866 1.        ]
 [0.21322552 0.75674407 0.92183239 0.938932   0.34979886]
 [0.90804948 0.48987528 0.82509259 0.07321753 0.31440096]]


__5.  How to find common values between two arrays?__

In [7]:
q5_array1=np.array([1,2,3,4,5,6,7,8,9,10])
q5_array2=np.array([1,3,5,7,9,11,13,15,17,19])
print("Common values between Array 1",q5_array1,"and Array 2",q5_array2," is",np.intersect1d(q5_array1,q5_array2))

Common values between Array 1 [ 1  2  3  4  5  6  7  8  9 10] and Array 2 [ 1  3  5  7  9 11 13 15 17 19]  is [1 3 5 7 9]


__6.How to get the dates of yesterday, today and tomorrow?__

In [11]:
import datetime
q6_Yesterday=datetime.date.today()-datetime.timedelta(1)
q6_Today=datetime.date.today()
q6_Tomorrow=datetime.date.today()+datetime.timedelta(1)
print("Yesterday:",q6_Yesterday,"\nToday:",q6_Today,"\nTomorrow:",q6_Tomorrow)

Yesterday: 2020-08-04 
Today: 2020-08-05 
Tomorrow: 2020-08-06


__7. Consider two random array A and B, check if they are equal__

In [16]:
q7_Array_A=np.random.randint(0,4,10)
q7_Array_B=np.random.randint(0,4,10)
print("Considered 2 Random Arrays where Array A:",q7_Array_A,"and Array B:",q7_Array_B)
if(np.allclose(q7_Array_A,q7_Array_B)):
    print("\nChecking if Array A and Array B are equal and Yes they are equal")
else:
    print("\nChecking if Array A and Array B are equal Oh No they are not equal")

Considered 2 Random Arrays where Array A: [1 3 1 3 3 2 2 0 1 3] and Array B: [3 1 3 1 0 1 2 2 0 3]

Checking if Array A and Array B are equal Oh No they are not equal


__8.Create random vector of size 10 and replace the maximum value by 0__

In [23]:
q8_vector=np.random.random(10)
print("Random Vector of Size 10:",q8_vector)
q8_vector[q8_vector.argmax()]=0
print("\nRandom Vector of Size 10 after replacing Maximum value by 0:",q8_vector)

Random Vector of Size 10: [0.31669883 0.24461635 0.72419992 0.2009973  0.53670692 0.80318657
 0.74026719 0.98558001 0.46384181 0.58858542]

Random Vector of Size 10 after replacing Maximum value by 0: [0.31669883 0.24461635 0.72419992 0.2009973  0.53670692 0.80318657
 0.74026719 0.         0.46384181 0.58858542]


__9. How to print all the values of an array?__

In [41]:
import sys
q9_array=np.random.randint(1,100,(40,40))
print("Created a Random Array of 40x40 and it is not printing all the values:\n",q9_array)
np.set_printoptions(threshold=sys.maxsize)
print("Created a Random Array of 40x40 and it is now printing all the values:\n",q9_array)


Created a Random Array of 40x40 and it is not printing all the values:
 [[68 20 14 ... 24 87 74]
 [37 92 41 ... 61 79 98]
 [ 4 28 82 ... 24 38 19]
 ...
 [69 33 86 ... 93 99 75]
 [ 6 73 12 ... 57 65 83]
 [21 72 93 ... 51 41 60]]
Created a Random Array of 40x40 and it is now printing all the values:
 [[68 20 14 25 79 57  4  5 82 23 62 80 96 78 43 37 29 90 97 82 45 73 81 43
  47 89 87 17 68 98 32 36  2 28 78  8 99 24 87 74]
 [37 92 41 98 81 44 72 25 84 67 57 72  8 15 83 52 99 70 59 42 45 42 30 19
  52 19 80 64 37  4 12 10 31 38 31 18 61 61 79 98]
 [ 4 28 82 79 70 25 92 21  6 43 24 37 19 56 91 12 29 78  1 44 55  9 57 20
   5 44  9 70 46 67 72 74 32 91 74  5 87 24 38 19]
 [47 19 77 73 29 34 17 10 54 90 11 31 13 40 18 31 74 25 33 86 71 87 17 91
  42  7 77 29 25 91  6 48 35 76 50 91 66 73 35  2]
 [50 69 72 91 92 18 83 32 42  7 66 15  9 95 51 77 69 47 85 40 61 53 10  6
   5  1 59  3 37 58 56 88 91 95 98 15  6  5 34  3]
 [81 27 38 52 63 65 49 30 31 85 95 13 85 18 72 28 23 27 63 14 81 92 33 60
 

__10.Subtract the mean of each row of a matrix__

In [46]:
q10_matrix=np.random.rand(5,5)
print("Sample Matrix:\n",q10_matrix)
q10_matrix=q10_matrix-q10_matrix.mean(axis=1,keepdims=True)
print("\nMatrix after Subtracting the Mean of each row of a Matrix:\n",q10_matrix)

Sample Matrix:
 [[0.55646543 0.47817916 0.99892642 0.58931628 0.24486943]
 [0.43615998 0.89849987 0.070975   0.63734382 0.97247201]
 [0.56550694 0.00752947 0.35128586 0.5502118  0.18893665]
 [0.43178541 0.22988993 0.40957787 0.46306994 0.6284837 ]
 [0.81590317 0.43119588 0.21013203 0.31621283 0.97452385]]

Matrix after Subtracting the Mean of each row of a Matrix:
 [[-0.01708592 -0.09537218  0.42537507  0.01576494 -0.32868191]
 [-0.16693016  0.29540974 -0.53211513  0.03425369  0.36938187]
 [ 0.2328128  -0.32516468  0.01859171  0.21751766 -0.14375749]
 [-0.00077596 -0.20267144 -0.0229835   0.03050857  0.19592233]
 [ 0.26630962 -0.11839768 -0.33946152 -0.23338072  0.42493029]]


__11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?__

In [54]:
q11_vector1=np.random.randint(1,20,10)
q11_vector2=np.random.randint(0,10,10)
q11_vector3=q11_vector1[q11_vector2]+1
print("Vector 1:\n",q11_vector1,"\nVector 2:\n",q11_vector2,"\nVector 1 after adding 1 to each element indexed by a Vector 2 is:\n",q11_vector3)

Vector 1:
 [ 9  1  5  7  1  5  9  1 11 14] 
Vector 2:
 [1 7 9 3 2 8 9 5 1 0] 
Vector 1 after adding 1 to each element indexed by a Vector 2 is:
 [ 2  2 15  8  6 12 15  6  2 10]


__12.How to get the diagonal of a dot product?__

In [57]:
q12_Array1=np.random.randint(1,10,(3,3))
q12_Array2=np.random.randint(11,20,(3,3))
print("Random Array 1:\n",q12_Array1,"\nRandom Array 2:\n",q12_Array2,"\nDot Product of Array 1 and Array 2:\n",np.dot(q12_Array1,q12_Array2),"\nDiagonal Elements of Dot Product:\n",np.diag(np.dot(q12_Array1,q12_Array2)))

Random Array 1:
 [[5 6 1]
 [2 6 6]
 [1 4 5]] 
Random Array 2:
 [[13 18 19]
 [15 13 16]
 [14 16 15]] 
Dot Product of Array 1 and Array 2:
 [[169 184 206]
 [200 210 224]
 [143 150 158]] 
Diagonal Elements of Dot Product:
 [169 210 158]


__13.How to find the most frequent value in an array?__

In [60]:
q13_Array=np.random.randint(1,10,100)
print("Random Array:\n",q13_Array,"\nMost frequent Value of the Random Array:\n",np.bincount(q13_Array).argmax())

Random Array:
 [9 4 3 7 8 2 3 1 1 8 9 7 2 2 6 8 7 2 4 3 2 8 3 3 1 5 7 5 2 8 9 9 8 1 9 2 9
 6 3 8 9 1 4 3 3 9 4 2 8 8 8 5 6 3 3 1 1 1 7 3 7 1 4 7 8 7 7 1 7 9 2 7 9 6
 8 6 9 1 1 7 7 1 5 5 2 6 8 9 7 1 7 3 5 7 8 7 7 8 4 1] 
Most frequent Value of the Random Array:
 7


__14.How to get the n largest values of an array__

In [66]:
q14_Array=np.arange(100)
print("Random Array:\n",q14_Array)
q14_N=int(input("\nEnter the Value of N:"))
print("\n",q14_N,"Largest Values of the Random Array:\n",q14_Array[np.argsort(q14_Array)[-q14_N:]])


Random Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]

Enter the Value of N:10

 10 Largest Values of the Random Array:
 [90 91 92 93 94 95 96 97 98 99]


__15.How to create a record array from a regular array?__

In [70]:
q15_Array1=np.random.randint(1,10,(3,3))
q15_Array2=np.core.records.fromarrays(q15_Array1.T,names='r1,r2,r3',formats='i8, i8, i8')
print("Regular Array:\n",q15_Array1,"\nRecord Array:\n",q15_Array2)

Regular Array:
 [[2 5 6]
 [7 3 8]
 [7 2 2]] 
Record Array:
 [(2, 5, 6) (7, 3, 8) (7, 2, 2)]
